apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/secret: 96cd4fed1196e465195ea6d1468d404adc9c0c9a466ec0c80d611f468ac8cfbd
  creationTimestamp: "2026-03-22T21:30:48Z"
  generateName: authentik-server-564b7c9bcb-
  generation: 1
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: authentik
    app.kubernetes.io/version: 2026.2.0
    helm.sh/chart: authentik-2026.2.1
    pod-template-hash: 564b7c9bcb
  name: authentik-server-564b7c9bcb-wf2gm
  namespace: auth
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: authentik-server-564b7c9bcb
    uid: 1cf74b49-6451-48fa-b7b2-e2b4295a41e3
  resourceVersion: "127329"
  uid: c77dcb7c-e3aa-4973-b8c0-495cdca28761
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: server
              app.kubernetes.io/instance: authentik
              app.kubernetes.io/name: authentik
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - args:
    - server
    env:
    - name: AUTHENTIK_LISTEN__HTTP
      value: 0.0.0.0:9000
    - name: AUTHENTIK_LISTEN__HTTPS
      value: 0.0.0.0:9443
    - name: AUTHENTIK_LISTEN__METRICS
      value: 0.0.0.0:9300
    envFrom:
    - secretRef:
        name: authentik
    image: ghcr.io/goauthentik/server:2026.2.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /-/health/live/
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    name: server
    ports:
    - containerPort: 9000
      name: http
      protocol: TCP
    - containerPort: 9443
      name: https
      protocol: TCP
    - containerPort: 9300
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /-/health/ready/
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
    startupProbe:
      failureThreshold: 60
      httpGet:
        path: /-/health/live/
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tvxcq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: deb13-k3s
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-tvxcq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-03-22T21:30:49Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-03-22T21:30:48Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-03-22T21:30:48Z"
    message: 'containers with unready status: [server]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-03-22T21:30:48Z"
    message: 'containers with unready status: [server]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-03-22T21:30:48Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 200m
      memory: 512Mi
    containerID: containerd://310143ca8c877611fb9418758f6dc32dfa753a37cf09455b0a585ac96654883f
    image: ghcr.io/goauthentik/server:2026.2.0
    imageID: ghcr.io/goauthentik/server@sha256:cfd955129ff142be93e7818682a04194b39c2ae8909a33f18e98b055baac27bf
    lastState: {}
    name: server
    ready: false
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
    restartCount: 0
    started: false
    state:
      running:
        startedAt: "2026-03-22T21:30:49Z"
    user:
      linux:
        gid: 1000
        supplementalGroups:
        - 1000
        uid: 1000
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tvxcq
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 100.68.81.91
  hostIPs:
  - ip: 100.68.81.91
  - ip: fd7a:115c:a1e0::8735:515b
  observedGeneration: 1
  phase: Running
  podIP: 10.42.0.134
  podIPs:
  - ip: 10.42.0.134
  - ip: fd00:42::86
  qosClass: Burstable
  startTime: "2026-03-22T21:30:48Z"
