---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgAlLYm7XPZ51fwwjNdUM2xWevjSOTOwA+xKJYB+zrWDDasJ5OTTk1ENdwSZd7IHwRs/DheA/MAr+YUaZoolJP9iSojhNuSHq9VTMvtvjEpPp5p9c22wI/caio5o12TAZ0Lbq2988QV5YlSlX8RXXIw1e05c1J56lsY0V6eJJ2JBaq2UkG9t/XcZooCLRj7tO5EVsEGF94SGwOezwcPDuiuGJWkHNgdl3WvecsuXxFjvYeWm6gzl30FoRs0zuR1FyyZRmrVmMzwLsRiV+I8BSgqilmyYYQP0ojKnUvVp1kbECaPs6PiAgDRG7NY1zz4pfUoLrayhIhwd//rp3p2onOtaickjEhmXaEb7pd694Jt8+uVxDBxhSqPzNJL4humcf2anYoRqjMmHC4hLv1MNd4+38ZBYI+AmTfEEwYydsECTQYyuCGVvQNltqylKJieR5S7TsjwI1uAQ4Kd5+GG+70H8Sn3CTFDlM9e457t0vcm26svM4ji0RF67B/DrABpnO6mUJeGsJgkov6vnKoET/h88iZUABCnp26GhbRZHKceRtN/0uLuBU4UwQhSO1nltOmcmfIOsXb8zE5gd8EBkeS9Ks+rxcAc5dj5z6A+/fc+jkhzMRSFTzxYeInPYurIvZK4hxKQZ3ve/nU8wDdwsnb148DzE5oGSckmVjAGFUptwX5UoAUPQFJL8JJe4GMBXE+DZAoP0YeZRH/op+57OP6wMR751vR5GIIEFJAIbqPN97X2yzgfCIByUDwkoNsdi7lH7VIMBvVs1Qr1jXjxbqENlZH6NhGK43k6HFtALFAD1gwRSEwO26SpQI+5XKHenPBCBCIcC40Qk9nrs3JYRKPyGnKuhjhaa
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
