bases:
- bases/default.yaml.gotmpl
---

helmfiles:
# Layer 1 — Operators et infra transverse
- path: releases/infra/cert-manager.yaml.gotmpl
- path: releases/infra/nfs-provisioner.yaml.gotmpl
- path: releases/infra/local-config-storageclass.yaml.gotmpl
- path: releases/infra/cnpg.yaml.gotmpl
- path: releases/infra/traefik.yaml.gotmpl
- path: releases/infra/velero.yaml.gotmpl

# Layer 2 — Auth namespace
- path: releases/auth/secrets.yaml.gotmpl
- path: releases/auth/authentik-db.yaml.gotmpl
- path: releases/auth/authentik.yaml.gotmpl
