apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'ghcr.io/kernelb00t'
    chart: paperless-ngx
    targetRevision: 2.20.15-1
    helm:
      values: |
        paperless:
          config:
            PAPERLESS_URL: "https://paper.thivillon.org"
            PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://paper.thivillon.org"
            PAPERLESS_TIME_ZONE: "Europe/Paris"
            PAPERLESS_OCR_LANGUAGE: "fra+eng"
            PAPERLESS_CONSUMER_RECURSIVE: "true"
            PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"
            PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
            PAPERLESS_EMAIL_TASK_CRON: "*/1 * * * *"
            PAPERLESS_EMAIL_HOST: "mail.thivillon.org"
            PAPERLESS_EMAIL_PORT: "465"
            PAPERLESS_EMAIL_HOST_USER: "paperless@thivillon.org"
            PAPERLESS_EMAIL_FROM: "titiPapers <paperless@thivillon.org>"
            PAPERLESS_EMAIL_USE_TLS: "true"
            PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
            PAPERLESS_REDIRECT_LOGIN_TO_SSO: "true"
            PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS: "true"
            PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
            
          # Grâce à la PR, ceci injectera désormais TOUTES les clés du secret 
          # (y compris OIDC et Mail) via envFrom !
          existingSecret: "paperless-secrets"

        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
          hosts:
            - host: "paper.thivillon.org"
              paths:
                - path: /
                  pathType: Prefix

        persistence:
          data:
            enabled: true
            storageClass: "local-config"
            size: 10Gi
          media:
            enabled: true
            storageClass: "local-config"
            size: 50Gi
          consume:
            enabled: true
            storageClass: "local-config"
            size: 5Gi

        cnpg:
          enabled: true
          instances: 1
          storage:
            size: 5Gi
            storageClass: "local-config"

        redis:
          enabled: true
          persistence:
            enabled: false

        gotenberg:
          enabled: true
        tika:
          enabled: true

        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 2Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: paperless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  - kind: PersistentVolumeClaim
    jsonPointers:
    - /spec/volumeName
