---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBe69uoAiAQPtVhWfjuCVF/pHhhlIo4wY2QmnbeXX+wQQ0fEf53Vyx3sGxVUXhNyHG5v5XzI5msMs7oo5/lk4r7VGnf4d3bzVjk5G6OdpDGOa3aSeS8rbv4jF6vBCtlDRRVmQwvbUiRcE2eEwWzP1KnXiV8q2ryksOzQj9mgmZINMqGVEuR7W+vOPaDemUUD95TWVy1eGRjaX4V/E+a0DOVi7yUNVb6gpVm1txxeHOwQKwAArlzAVPJgiayzqRTn7TtD0PF55+v49cgCYvVg9B1C/XYCElYAypbYEXRobQXCDDmm2eI+Zdr1kIOp7CNaIrAE7/70qSxPnMKEv+M5N/IHvYdNH6NxAFrilhfjwnuTInMfyeUA+JlmGRWmGl9rKcZ59mjJyUQXfV6500UTA3h1T+8Si6yX+ty/1wC+5Ec9rCkxO2gEiNaR34N32qnKtiGW9TWopifhHY9HyjTODmgW8Bk/zwFJ659TaD9o1cXHaYQDtJa3CEZLyUKT9OGBnBegjLdjS/Ypx2VQBELDylPa3CvqTgGL/5r2OuLj7fbNVRdlMfzDihqKSiw9S9YfhNJiy2W37RxPrMQZ1O7PUxRRG1qHm51SVebqiTxkn7SVpYuJnfdGC5QFyC65PTtlON+felSdzmShY8gY0rh8j3lDPUzh6GaeflfccSkktY99UqcwZWu4pY6+vtFaKraLBzoOesNtkHQxz+r/hw9VtIhjDSbuAqmgBVFIeZ05ozafYdV1Lh4qZfQu2XaulfgPivx/usIvkGRhRxN0ZLtE5su28NgUZ37Z9GJscZsfdU09YzjaDHplnf9yrsId2ZoPXvue9qlb1bic6Jo3TSSx8vAom60l52w/8XNvYL5MMeQIRjX41Mk4oT1SMbOMeRTNOGiae0E4G+Ovg==
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
