persistence:
  config:
    enabled: true
    storageClass: local-config
    size: 5Gi
  media:
    enabled: true
    existingClaim: media-data-pvc

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  hosts: []
  tls: []

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 4000m
    memory: 4Gi
