apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
  namespace: immich
type: kubernetes.io/basic-auth
stringData:
  username: immich
  # Remplace ceci par ton ancienne valeur IMMICH_DB_PASSWORD issue de .envrc
  password: "YOUR_IMMICH_DB_PASSWORD"
