---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientID: AgBQBK2adbq5npst5Ulk5+cqwr2eOxP+RDfn1IJAhfxM8zBsBLuesRZ81FIbRF4yu41KH68pY44OBZNs/WA7kRxMOkTphGyhoM0pakNRavZY2L78Nk6OYP/Z9Ik5ScX8p+I5yjQZ7U8iZ9/t7qKCWLnWGh6P0NBAq+EM/1j1Rlf8WtfKVZ4xbN3se1IX6/bmu+U9KXuzE0LmUkS2bg4pTgBGAzwRZ6u1KwliCdkgcYzudiK1RhzzIcCzsv26PjODgU2wPZPzAFnHMpJWajoPSmGDRyVA/CAigEY+U2kHLRwXdqavlvnO7eAAHvVR+ba2crLlCQu2C7rdr0S1EF6adfotfdxJan69Cb2QJ7TG1UIbr//dnjCFX07YfTvRJqNNwvpQI6BcrbWyCtEESg3oVx7ImNSSvdfCUuthY5oVYDnoJt8RPYCNLRFM242cibDUg6Sslv744w1oAyrfICur+9x5jH2cHQj2iSpJS8VOQ2AoLyKVhS9cVpqtd+/MvQiiLVJCSQL/8xLBCUiW5oBM4TEyFtkY+kIRw4HOoiJrCnpOYWuXqx7LagmsVilSgEfu/NIBVLEiQmvoD+0MFICrI3MxFZhCtkIj2E/m5WFZzQywy+cVeAjrYiEf/NX8NAT6zNnVWTII80dFiPXzTqKIvC4Ia6hRiZChkGPBa2+SDA6bp4iEpdmfp5OyTj+dpnknzRJPhqcTekHugQdA6E4UKu+1/lhHrbJGpSZ1iVCjApSMEhIlMO4S4O9tMKLJbVNBo4pRdLPk0esrhjv+1MCaXzOTxYCx6ItaGoQ=
    clientSecret: AgCiVmPzC++kesp0rZz5iHqkm0ljqqf4Usbvnwm5v5CrvTlNYQ06ZRrMDXaAaQEBSucHGqoUnup0gIFH3sL1uUKqvieplKlGbtMMp/bVhtTVfFMzuMi2aAHexr/PRVULyr7qUmXS571s4aydqx5fXSAhyIOAnmd/AIZx/czTpuYoQdgoxuZX8OZlD3lXb9FlAFmhf1vM4SGzUFHAvi5AXdHJwwmpc+eOAz0vOf/Al4MFb5Lzp+bYw6vx6b5zt6KdAj8uelrS5vkJSioAvrRD/oqwYkU+oDt5z9zYSbLZ04hJpcDQozkIiHrHZwpTkp1OKk6xpwb/4dcEvFtpWFmGNQM5wf4VzD3XwC19WSQUty8vgbF/+wzFreO4wjqzS7qpsBngppfaczQQj0kfc/s8RZfdfwWpADNxYHCVSooKxm+ZFSc+Cf4nDeXh5egTkFBgxW/aXQHX+D9Gklv4n8l1yh3jDr2gk/2sdnbAm7IeGVU5gGGK2iRC/N/ynNoY8oRpFNc2a+VuIQd/0xccpbxYK0jPPPc1cO89YvRMm+xrEXAjnow4juqS1wQaS1sZht3qo9d5WDM6DV2kZpZPq+JmUUGsf3+gnndjY2d66tuI5TyynDtkKQMJ8uZEcNDvVRE7fkUoo4JJ37bxAGjrdzG84b79NJ13FWtrfC+U4/7fbKiOIJnRGZB0dm+rSZj6If9Fl49WoNuUyukHOCvB4XYSLDeZcKhGfY70k5ogFO9k0Ejk3od0/g==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
