apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-webhook-secret
  namespace: argocd
spec:
  encryptedData:
    webhook-secret: AgArhqZkafiefKp/9L1jekAxEG8Rn4vMK83S9Uo2TtJ2ixZbidix22cKfrrvnsX17ba3EjA1oJfXZ9V27ba2b4ny8NtBMZ5QVCNcl+DpmwgkYdpkV+bBsbxXw3mPKzX6mEqpdEF6S+LqyQ1Q4M4uSwVEAgqXAMSCtKJqhLoqaQZfg9opcJ72j0QyKgAxMg45gSNlZB1mju2pbwRwrFjGek+u6aRtaTc8/wWrah7j+R3irXZagR/dmt1/2yLgwdVuzYazuN6T9o+TYgTZR6vUESrA1ADHF7pOH277BMSXmwO3Idm96kGQB+IicEpstYeVMhN13TPQPlAju1Rh8vPy6EpMoQ7DsEV4A+ySUGfpcj4Xibhy2Jhby+j4NrxxR786vqqj1atE4H3McNmjU+tpQU2NVVq8EbsrcgfELdntlWt3Chultzm9NCztd3jt5G5Wx3qxqYmZqI1xAgJSmwFZvkorEYDGBoycSvqMyVI4JNKyltiwul09vg6TCFDvum8+nxx5JoMFE8yPFPIeXDd+WoUrJvglWb1pl/jKoOeDV2zwQ9nhDCxTONUa1+nFtsEkG7QIAc+gTLMYJlkY1IBeRZeWPC1javqwrkM12gNL9kpMrMU7bNp8vXC4YnYeCOawR7moUwVLVJjtxAsWqsnzk66qlSC7dn/AfxRTogZ08aidWhMi4ohmf45KlUpMnTOeptsGJiPWJt9LbexObnTHnAbsPQ37FFaZ+ETM2mjJ3oAfzZmFT3Mq6YYeAXwUo2DXDHdRL3yeOpTaG8DdDs/FNlWf
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-webhook-secret
      namespace: argocd
