apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientID: AgCuAR1p+DY59e9y4s7M+Sp7kH2uo3UecH1IqQtPM8LtMtUvpsCxUKbLJTkxypOEi0ZZokwKBWMRI56zDEaQM3jMRBMsAENEjOVgbbMefSmJuJkShBwBFXPc0YvYxJQzua6ONrkOP9NxiGZ5BR+Pm2Z0oKBzjA5ezXahWcHwGPt2zqdGmnxYrXAhwlMSr7+tbYDvIfTAkStcXdIPV+dmbu+sXZZEitNSMEi7rEYNP+i6fehHVd9p19NaNCoN18WaQ8y1G2ATpWgsbA5psUMp0IDchpx4Y/QW5aAv4o663r/IBgJyVwGEeH1QsSjXe8rlJxzsvVGvhhx0ximGnsLfAm/0oAi2kHA4V3B5YTlOhxl3dOiKqOkufmU/AsGbm0vtNE1aRYJSfyrJztU+zwZMzMxRais1KoJ/d04O5R3r7zoWzlcJOQ1bjKfI3FxTsiT9qJK4Uhcobz2ZgE/N2HHYpWkgFEQEYB3BvodOxywXGyWwj+ynJCwwMv6KFrKcUrBoDwa5gfHyQt76t3901GlQG+5dxoKH5svPfCX0HjdBW19MsJod6M/SOTFxe5oPI0tzJUQGTA3S0QjO3utfjJwcHlyppPNXED+j006rzKVjC9xkZULsC2c8Di52Xsl0/WvQoiYllXHMIAJfvFTmJvMvafliqEKIcNQmWXR/4MLPDivUrLoIRmk3R6v8t++BN5i54HEjGv+VYvPrf8/nBMvEL07DWUaMqZPl5vPmVXdJvfJOVbA6GODpi3zR+4+YVv075XUDV08CrdPaLtS3NV4Mhx496eSuws7ywiA=
    clientSecret: AgDDHwKWOKJSnEs2tKlESn+dZRHRUnaG4XgVnD+KlLrBzzMRsljb6dACohL/u8cmpLtcOqMqU6mctX4v3hdOmlti1/XGXFb/Rt/VUt0nZVoF2eSRQJ9bGbNsJ8il1AkNleVwAHHfm9ENTyKB+T4YTNPfvGSmNcuN6ICwWKxuJg5QKxlyC3UCihZLLvYosd8ygY8TAoujqJmOvS+Fs8mKpM8ZaqKn13yUzDrOOzNK2who9XDuHz6z1XfFUpikAl5HmDyqoSOi3lGitcMInVrdbgXr6inWNaw2Kae1gmGE/KqmlrK0nEKXBrTC6wUTgmRaCKA9FCLSZVfEvAJSGNrZkzu7APRXYcgdjJ69R4HEwgn6NdRCBOvQ3SNuXjqXU07nbFzFWwjdR6j2rsGfavnVWHj5m2SDTWn9DpYZErVi/8kiS8fSVfpQAGbHSv7HZ6ohDeBrdZV0s+ySNZ6hUBg8QBvrowp5FTakNMRLwFTUYUrwVuqOf5yqTS+HHJwBwh6EAhzQpQy6ClgtAyv9OygIxN0hKeANkV5iM+qvpzjisnI64t/Kfa+jTlYmK4h20qMm2aWJ6hPaSGRXX2GRyt7pfyLvXL3GIyGjifE3oRpnf+DxoYhDezruKoPCgcAVF5XLScEO5Wip4xi1RNuyEkeTRv8ZbNwBA7DxCQ+fmdKO64b/r300k0NfAw5dwyXsLizBxLT09k5Jl5LsFWTvjzsHILxJbIfcQT6veKugiIxkSm3SFakJJQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
