apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-webhook-secret
  namespace: argocd
spec:
  encryptedData:
    webhook-secret: AgByfAd3BlFbm/iNXwHtZlF3hiKHIWMbyhgdyEL6N5K1hhcy/fVz9vN+sEklicZ9svSlw1y5aO2bmV0QPFtFFPX34/95sbbmW6oHk47tKj2KyXDgjOK8HvT/VqH7Gj8c3mGU/5bus2XyA6HoSrn5Fxh9wAiy91GQ7DJchfuFLgFNgBSatK4VavlUus//7ZTjukKoZMS+kAwhI+29mm2yU7mqBoQstabC9itS8YV5FG1tttVAftP6VicugZGRR9fbPpeecbX2s1KKS8VlcVWBFGzn6yYPIJ7d86qL6ADfgAFdSVeHngptVFaCvnVp5ur3ihmHYR+7hhKN7ffAZJVCcw++7ZKKRenkfSXkCj1RunSG5UispmeqrT8oIWUet5ZsbvTtdv8MVwDyNuByyifwVhUSaTj7FJOPBoPRGZ8iGpVxfnex73GerK4gohm4+ZMv5U3NAj1GqglS8OUXl59GsYH7dPhweIJeXgxnWz1BRLJ7uhWNu9S/rO3fac33mF5XVIZOPe10XA6GohK6ci274WXf61cIybp+O8eaggwb+tkWQ87PAJeWDOq5frv/mx4e1nRkhBxrW/8C/UqvgmO1G2kxWjJPa0zkv+ST9NVLdUkDDz/dRwnI4P+GHd+d1U6yhbK8k9gE0X1Uc01s1qn5qY01Dbplsz53o/er+NAwD8c4lCS6lAtzHDY4Rqho/ES2hWRtqSvBBeYf61XPpX96gjLCkGcjuseYdf7WiIyLzlUvSMnp6tnJzZVp2opq+oRe3VWQ9k0vsCxcVf7dmL2Q8c2X
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-webhook-secret
      namespace: argocd
